# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = S:\IIT\Thesis\cmake-3.20.2-windows-x86_64\cmake-3.20.2-windows-x86_64\bin\cmake.exe

# The command to remove a file.
RM = S:\IIT\Thesis\cmake-3.20.2-windows-x86_64\cmake-3.20.2-windows-x86_64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "S:\IIT\Thesis\Ion Migration Code\narrowbandgap in tandem checker"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "S:\IIT\Thesis\Ion Migration Code\narrowbandgap in tandem checker\build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	S:\IIT\Thesis\cmake-3.20.2-windows-x86_64\cmake-3.20.2-windows-x86_64\bin\cmake-gui.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	S:\IIT\Thesis\cmake-3.20.2-windows-x86_64\cmake-3.20.2-windows-x86_64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "S:\IIT\Thesis\Ion Migration Code\narrowbandgap in tandem checker\build\CMakeFiles" "S:\IIT\Thesis\Ion Migration Code\narrowbandgap in tandem checker\build\\CMakeFiles\progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "S:\IIT\Thesis\Ion Migration Code\narrowbandgap in tandem checker\build\CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/CurrentContinuityEquation.obj: src/CurrentContinuityEquation.cpp.obj
.PHONY : src/CurrentContinuityEquation.obj

# target to build an object file
src/CurrentContinuityEquation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/CurrentContinuityEquation.cpp.obj
.PHONY : src/CurrentContinuityEquation.cpp.obj

src/CurrentContinuityEquation.i: src/CurrentContinuityEquation.cpp.i
.PHONY : src/CurrentContinuityEquation.i

# target to preprocess a source file
src/CurrentContinuityEquation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/CurrentContinuityEquation.cpp.i
.PHONY : src/CurrentContinuityEquation.cpp.i

src/CurrentContinuityEquation.s: src/CurrentContinuityEquation.cpp.s
.PHONY : src/CurrentContinuityEquation.s

# target to generate assembly for a file
src/CurrentContinuityEquation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/CurrentContinuityEquation.cpp.s
.PHONY : src/CurrentContinuityEquation.cpp.s

src/IterativeSolver.obj: src/IterativeSolver.cpp.obj
.PHONY : src/IterativeSolver.obj

# target to build an object file
src/IterativeSolver.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/IterativeSolver.cpp.obj
.PHONY : src/IterativeSolver.cpp.obj

src/IterativeSolver.i: src/IterativeSolver.cpp.i
.PHONY : src/IterativeSolver.i

# target to preprocess a source file
src/IterativeSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/IterativeSolver.cpp.i
.PHONY : src/IterativeSolver.cpp.i

src/IterativeSolver.s: src/IterativeSolver.cpp.s
.PHONY : src/IterativeSolver.s

# target to generate assembly for a file
src/IterativeSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/IterativeSolver.cpp.s
.PHONY : src/IterativeSolver.cpp.s

src/PoissonEquation.obj: src/PoissonEquation.cpp.obj
.PHONY : src/PoissonEquation.obj

# target to build an object file
src/PoissonEquation.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/PoissonEquation.cpp.obj
.PHONY : src/PoissonEquation.cpp.obj

src/PoissonEquation.i: src/PoissonEquation.cpp.i
.PHONY : src/PoissonEquation.i

# target to preprocess a source file
src/PoissonEquation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/PoissonEquation.cpp.i
.PHONY : src/PoissonEquation.cpp.i

src/PoissonEquation.s: src/PoissonEquation.cpp.s
.PHONY : src/PoissonEquation.s

# target to generate assembly for a file
src/PoissonEquation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/PoissonEquation.cpp.s
.PHONY : src/PoissonEquation.cpp.s

src/PostProcessing.obj: src/PostProcessing.cpp.obj
.PHONY : src/PostProcessing.obj

# target to build an object file
src/PostProcessing.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/PostProcessing.cpp.obj
.PHONY : src/PostProcessing.cpp.obj

src/PostProcessing.i: src/PostProcessing.cpp.i
.PHONY : src/PostProcessing.i

# target to preprocess a source file
src/PostProcessing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/PostProcessing.cpp.i
.PHONY : src/PostProcessing.cpp.i

src/PostProcessing.s: src/PostProcessing.cpp.s
.PHONY : src/PostProcessing.s

# target to generate assembly for a file
src/PostProcessing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/PostProcessing.cpp.s
.PHONY : src/PostProcessing.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... main
	@echo ... src/CurrentContinuityEquation.obj
	@echo ... src/CurrentContinuityEquation.i
	@echo ... src/CurrentContinuityEquation.s
	@echo ... src/IterativeSolver.obj
	@echo ... src/IterativeSolver.i
	@echo ... src/IterativeSolver.s
	@echo ... src/PoissonEquation.obj
	@echo ... src/PoissonEquation.i
	@echo ... src/PoissonEquation.s
	@echo ... src/PostProcessing.obj
	@echo ... src/PostProcessing.i
	@echo ... src/PostProcessing.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

